version: '3'

services:

  ########## GENERAL ##########

  caddy-gateway:
    image: caddy
    container_name: "ap-caddy-gateway"
    networks:
      - ap-network
      - ap-internal
    env_file:
      - ./.env
    volumes:
      - ./infrastructure/caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./infrastructure/caddy/data:/data
      - ./infrastructure/caddy/config:/config
    ports:
      - 80:80/tcp
      - 443:443/tcp
      - 443:443/udp
      - 8080:8080
    restart: unless-stopped

  varnish:
    image: varnish
    container_name: "ap-varnish"
    networks:
      - ap-internal
    env_file:
      - ./.env
    volumes:
      - ./infrastructure/varnish/default.vcl:/etc/varnish/default.vcl
    ports:
      - 6180:80
    depends_on:
      - caddy-gateway
      - keycloak
      - graphql-gateway

  email:
    image: mailhog/mailhog
    container_name: email-service
    networks:
      - ap-internal
    env_file:
      - ./.env
    ports:
      - 8025:8025
      - 1025:1025

  graphql-gateway:
    image: graphql/gateway
    container_name: "ap-graphql-gateway"
    networks:
      - ap-internal
    environment:
      GRAPHQL_URL_0: "https://game:8181/graphql"
      GRAPHQL_UPDATE_GATEWAY: true
      GRAPHQL_UPDATE_GATEWAY_INTERVAL_MS: 60000
    ports:
      - 6181:80
    depends_on:
      - game

  ########## AUTHENTIFICATION - KEYCLOAK ##########
  
  keycloak:
    image: jboss/keycloak
    container_name: "ap-keycloak"
    networks:
      - ap-internal
      - ap-auth
    env_file:
      - ./.env
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: keycloak-db
      DB_DATABASE: ${KEYCLOAK_DB_NAME}
      DB_PORT: 5432
      DB_USER: ${KEYCLOAK_DB_USER}
      DB_SCHEMA: public
      DB_PASSWORD: ${KEYCLOAK_DB_PWD}
      KEYCLOAK_USER: ${KEYCLOAK_USER}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PWD}
      PROXY_ADDRESS_FORWARDING: "true"
    ports:
      - 8180:8080
    depends_on:
      - keycloak-db

  keycloak-db:
    image: postgres
    container_name: "ap-keycloak-db"
    networks:
      - ap-auth
    volumes:
      - ./infrastructure/keycloak/data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${KEYCLOAK_DB_NAME}
      POSTGRES_USER: ${KEYCLOAK_DB_USER}
      POSTGRES_PASSWORD: ${KEYCLOAK_DB_PWD}
  
  ########## GAMESERVICE ##########

  game-caddy:
    image: caddy
    container_name: "game-caddy"
    networks:
      - ap-internal
      - ap-game
    env_file:
      - ./.env
    volumes:
      - ./GameService:/var/www/html
      - game_php_socket:/var/run/php
      - ./GameService/Caddyfile:/etc/caddy/Caddyfile
      - ./GameService/caddy/data:/data
      - ./GameService/caddy/config:/config
    ports:
      - 8181:80

  game:
    image: thecodingmachine/php:8.0-v4-fpm
    container_name: "ap-game-service"
    networks:
      - ap-game
    env_file:
      - ./.env
    volumes:
      - ./GameService:/var/www/html
      - game_php_socket:/var/run/php
    ports:
      - 8182:9000
    environment:
      PHP_INI_MEMORY_LIMIT: "1G"
      PHP_EXTENSION_PGSQL: "1"
      PHP_EXTENSION_MYSQLI: "0"
      APP_ENV: "${APP_ENV}"
      DATABASE_URL: "postgres://${GAME_DB_USER}:${GAME_DB_PWD}@game-db:5432/game?sslmode=disable&charset=utf8"
      PHP_EXTENSION_XDEBUG: "1"
      PHP_INI_XDEBUG__REMOTE_AUTOSTART: "1"
    depends_on:
      - game-db

  game-db:
    image: postgres
    container_name: "ap-game-db"
    networks:
      - ap-game
    volumes:
      - ./infrastructure/servicesDb/game:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "game"
      POSTGRES_USER: ${GAME_DB_USER}
      POSTGRES_PASSWORD: ${GAME_DB_PWD}

volumes:
  game_php_socket:

networks:
  ap-network:
    external: true
  ap-internal:
    external: false
    driver: bridge
  ap-auth:
    external: false
    driver: bridge
  ap-game:
    external: false
    driver: bridge
